services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./uploads:/var/www/html/uploads
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=fortipass
      - MYSQL_PASSWORD=fortipass_secret
      - MYSQL_DATABASE=fortipass
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_DATABASE: fortipass
      MYSQL_USER: fortipass
      MYSQL_PASSWORD: fortipass_secret
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: